/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CALCPROG 0x30090949
#define CALCVERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_2(int *, CLIENT *);
extern  int * add_2_svc(int *, struct svc_req *);
#define MUL 2
extern  int * mul_2(int *, CLIENT *);
extern  int * mul_2_svc(int *, struct svc_req *);
#define INIT 3
extern  void * init_2(int *, CLIENT *);
extern  void * init_2_svc(int *, struct svc_req *);
extern int calcprog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_2();
extern  int * add_2_svc();
#define MUL 2
extern  int * mul_2();
extern  int * mul_2_svc();
#define INIT 3
extern  void * init_2();
extern  void * init_2_svc();
extern int calcprog_2_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
